export interface Channel {
  id: string;
  name: string;
  category: string;
  url: string;
  imageUrl: string;
  color: string;
  initials: string;
}

export const CATEGORIES_CONFIG = [
  { name: "Notícias", color: "#3b82f6" },
  { name: "Abertos", color: "#22c55e" },
  { name: "Esportes", color: "#f59e0b" },
  { name: "Streaming", color: "#8b5cf6" },
  { name: "Infantil", color: "#ec4899" },
  { name: "Filmes e Séries", color: "#ef4444" },
  { name: "Religiosos", color: "#06b6d4" },
  { name: "Documentários", color: "#10b981" },
  { name: "Música", color: "#d946ef" }
];

export const CATEGORIES = CATEGORIES_CONFIG.map(c => c.name);

export const CHANNELS: Channel[] = [
  // NOTÍCIAS
  { id: 'cnn-brasil', name: 'CNN Brasil', category: 'Notícias', url: 'https://canais.free.nf/player/cnn.html', imageUrl: '', color: '#3b82f6', initials: 'CB' },
  { id: 'cnn-brasil-op2', name: 'CNN Brasil OP2', category: 'Notícias', url: 'https://redecanaistv.be/player3/ch.php?canal=cnnbrasil', imageUrl: '', color: '#10b981', initials: 'CB' },
  { id: 'cnn-money', name: 'CNN Money', category: 'Notícias', url: 'https://redecanaistv.be/player3/ch.php?canal=cnnbrasilmoney', imageUrl: '', color: '#d946ef', initials: 'CM' },
  { id: 'globo-news', name: 'Globo News', category: 'Notícias', url: 'https://rdcanais.com/globonews', imageUrl: '', color: '#ef4444', initials: 'GN' },
  { id: 'globo-news-op2', name: 'Globo News OP2', category: 'Notícias', url: 'https://redecanaistv.be/player3/ch.php?canal=globonews', imageUrl: '', color: '#ef4444', initials: 'GN' },
  { id: 'sbt-news', name: 'SBT News', category: 'Notícias', url: 'https://canais.free.nf/player/sbtnews.html', imageUrl: '', color: '#f43f5e', initials: 'SN' },
  { id: 'band-news', name: 'Band News', category: 'Notícias', url: 'https://redecanaistv.be/player3/ch.php?canal=bandnews', imageUrl: '', color: '#e11d48', initials: 'BN' },
  { id: 'record-news', name: 'Record News', category: 'Notícias', url: 'https://anym3u8player.com/tv/p.php?url=https://rnw-rn-samsungtvplus.otteravision.com/rnw/rn/rnw_rn.m3u8', imageUrl: '', color: '#3b82f6', initials: 'RN' },
  { id: 'cnbc-brasil', name: 'CNBC Brasil', category: 'Notícias', url: 'https://redecanaistv.be/player3/ch.php?canal=cnbcbrasil', imageUrl: '', color: '#10b981', initials: 'CB' },

  // ABERTOS
  { id: 'globo-sp', name: 'Globo SP', category: 'Abertos', url: 'http://s2.micineovs.com/GLOBO/index.m3u8?token=16FOTt9Ae2m8', imageUrl: '', color: '#22c55e', initials: 'GS' },
  { id: 'globo-sp-op2', name: 'Globo SP OP2', category: 'Abertos', url: 'https://redecanaistv.be/player3/ch.php?canal=bobosp', imageUrl: '', color: '#22c55e', initials: 'GS' },
  { id: 'globo-rj', name: 'Globo RJ', category: 'Abertos', url: 'https://rdcanais.com/globorj', imageUrl: '', color: '#ec4899', initials: 'GR' },
  { id: 'globo-rj-op2', name: 'Globo RJ OP2', category: 'Abertos', url: 'https://redecanaistv.be/player3/ch.php?canal=boborj', imageUrl: '', color: '#ef4444', initials: 'GR' },
  { id: 'globo-mg', name: 'Globo MG', category: 'Abertos', url: 'https://redecanaistv.be/player3/ch.php?canal=bobomg', imageUrl: '', color: '#10b981', initials: 'GM' },
  { id: 'globo-ba', name: 'Globo BA', category: 'Abertos', url: 'http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8', imageUrl: '', color: '#ef4444', initials: 'GB' },
  { id: 'globo-nordeste', name: 'Globo Nordeste', category: 'Abertos', url: 'https://redecanaistv.be/player3/ch.php?canal=bobonordeste', imageUrl: '', color: '#ec4899', initials: 'GN' },
  { id: 'sbt', name: 'SBT', category: 'Abertos', url: 'https://canais.free.nf/player/sbt.html', imageUrl: '', color: '#f59e0b', initials: 'SB' },
  { id: 'sbt-op2', name: 'SBT OP2', category: 'Abertos', url: 'https://redecanaistv.be/player3/ch.php?canal=sbt', imageUrl: '', color: '#f59e0b', initials: 'SB' },
  { id: 'band', name: 'Band', category: 'Abertos', url: 'https://beyond.spalla.io/player/?live=0195cdf3-d8d8-74b6-9516-6c79c06bcec8', imageUrl: '', color: '#3b82f6', initials: 'BA' },
  { id: 'band-op2', name: 'Band OP2', category: 'Abertos', url: 'https://redecanaistv.be/player3/ch.php?canal=band', imageUrl: '', color: '#3b82f6', initials: 'BO' },
  { id: 'record-tv', name: 'Record TV', category: 'Abertos', url: 'https://rdcanais.com/record', imageUrl: '', color: '#f59e0b', initials: 'RT' },
  { id: 'record-tv-op2', name: 'Record TV OP2', category: 'Abertos', url: 'https://redecanaistv.be/player3/ch.php?canal=record', imageUrl: '', color: '#f59e0b', initials: 'RT' },
  { id: 'rede-tv', name: 'Rede TV', category: 'Abertos', url: 'https://canais.free.nf/player/redetv.html', imageUrl: '', color: '#3b82f6', initials: 'R1' },
  { id: 'rede-tv-op2', name: 'Rede TV OP2', category: 'Abertos', url: 'https://redecanaistv.be/player3/ch.php?canal=redetv', imageUrl: '', color: '#3b82f6', initials: 'R2' },
  { id: 'tv-brasil', name: 'TV Brasil', category: 'Abertos', url: 'https://canais.free.nf/player/tvbrasil.html', imageUrl: '', color: '#22c55e', initials: 'TB' },
  { id: 'tv-cultura', name: 'TV Cultura', category: 'Abertos', url: 'https://canais.free.nf/player/cultura.html', imageUrl: '', color: '#10b981', initials: 'TC' },
  { id: 'tv-gazeta', name: 'TV Gazeta', category: 'Abertos', url: 'https://geo.dailymotion.com/player.html?video=x8ttlxm', imageUrl: '', color: '#8b5cf6', initials: 'TG' },
  { id: 'tv-futura', name: 'TV Futura', category: 'Abertos', url: 'https://canais.free.nf/player/futura.html', imageUrl: '', color: '#f59e0b', initials: 'TF' },

  // ESPORTES
  { id: 'sportv-1', name: 'SporTV 1', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=sportv1', imageUrl: '', color: '#3b82f6', initials: 'S1' },
  { id: 'sportv-1-op2', name: 'SporTV 1 OP2', category: 'Esportes', url: 'https://rdcanais.com/sportvalternativo', imageUrl: '', color: '#3b82f6', initials: 'S1' },
  { id: 'sportv-2', name: 'SporTV 2', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=sportv2', imageUrl: '', color: '#22c55e', initials: 'S2' },
  { id: 'sportv-2-op2', name: 'SporTV 2 OP2', category: 'Esportes', url: 'https://rdcanais.com/sportv2alternativo', imageUrl: '', color: '#22c55e', initials: 'S2' },
  { id: 'sportv-3', name: 'SporTV 3', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=sportv3', imageUrl: '', color: '#ec4899', initials: 'S3' },
  { id: 'sportv-3-op2', name: 'SporTV 3 OP2', category: 'Esportes', url: 'https://rdcanais.com/sportv3alternativo', imageUrl: '', color: '#ec4899', initials: 'S3' },
  { id: 'espn-1', name: 'ESPN 1', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=espn', imageUrl: '', color: '#ef4444', initials: 'E1' },
  { id: 'espn-1-op2', name: 'ESPN 1 OP2', category: 'Esportes', url: 'https://rdcanais.com/espn', imageUrl: '', color: '#ef4444', initials: 'E1' },
  { id: 'espn-2', name: 'ESPN 2', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=espn2', imageUrl: '', color: '#f59e0b', initials: 'E2' },
  { id: 'espn-2-op2', name: 'ESPN 2 OP2', category: 'Esportes', url: 'https://rdcanais.com/espn2', imageUrl: '', color: '#f59e0b', initials: 'E2' },
  { id: 'espn-3', name: 'ESPN 3', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=espn3', imageUrl: '', color: '#8b5cf6', initials: 'E3' },
  { id: 'espn-3-op2', name: 'ESPN 3 OP2', category: 'Esportes', url: 'https://rdcanais.com/espn3', imageUrl: '', color: '#8b5cf6', initials: 'E3' },
  { id: 'espn-4', name: 'ESPN 4', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=espn4', imageUrl: '', color: '#ec4899', initials: 'E4' },
  { id: 'espn-4-op2', name: 'ESPN 4 OP2', category: 'Esportes', url: 'https://rdcanais.com/espn4', imageUrl: '', color: '#ec4899', initials: 'E4' },
  { id: 'espn-5', name: 'ESPN 5', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=espn5', imageUrl: '', color: '#ef4444', initials: 'E5' },
  { id: 'espn-5-op2', name: 'ESPN 5 OP2', category: 'Esportes', url: 'https://rdcanais.com/espn5', imageUrl: '', color: '#ef4444', initials: 'E5' },
  { id: 'espn-6', name: 'ESPN 6', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=espn6', imageUrl: '', color: '#3b82f6', initials: 'E6' },
  { id: 'espn-6-op2', name: 'ESPN 6 OP2', category: 'Esportes', url: 'https://rdcanais.com/espn6', imageUrl: '', color: '#3b82f6', initials: 'E6' },
  { id: 'band-sports', name: 'Band Sports', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=bandsports', imageUrl: '', color: '#10b981', initials: 'BS' },
  { id: 'premiere-clubes', name: 'Premiere Clubes', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=premiereclubes', imageUrl: '', color: '#f59e0b', initials: 'PC' },
  { id: 'premiere-clubes-op2', name: 'Premiere Clubes OP2', category: 'Esportes', url: 'https://rdcanais.com/premiereclubes', imageUrl: '', color: '#f59e0b', initials: 'PC' },
  { id: 'premiere-2', name: 'Premiere 2', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=premiere2', imageUrl: '', color: '#f43f5e', initials: 'P2' },
  { id: 'premiere-3', name: 'Premiere 3', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=premiere3', imageUrl: '', color: '#f43f5e', initials: 'P3' },
  { id: 'premiere-4', name: 'Premiere 4', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=premiere4', imageUrl: '', color: '#f43f5e', initials: 'P4' },
  { id: 'premiere-5', name: 'Premiere 5', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=premiere5', imageUrl: '', color: '#f43f5e', initials: 'P5' },
  { id: 'premiere-6', name: 'Premiere 6', category: 'Esportes', url: 'https://rdcanais.com/premiere6alternativo', imageUrl: '', color: '#f43f5e', initials: 'P6' },
  { id: 'premiere-7', name: 'Premiere 7', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=premiere7', imageUrl: '', color: '#f43f5e', initials: 'P7' },
  { id: 'premiere-8', name: 'Premiere 8', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=premiere8', imageUrl: '', color: '#f43f5e', initials: 'P8' },
  { id: 'combate', name: 'Combate', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=combate', imageUrl: '', color: '#0ea5e9', initials: 'CO' },
  { id: 'combate-op2', name: 'Combate OP2', category: 'Esportes', url: 'https://rdcanais.com/combate', imageUrl: '', color: '#0ea5e9', initials: 'CO' },
  { id: 'ufc-fight-pass', name: 'UFC Fight Pass', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=ufcfightpass', imageUrl: '', color: '#ef4444', initials: 'UF' },
  { id: 'ufc-fight-pass-op2', name: 'UFC Fight Pass OP2', category: 'Esportes', url: 'https://rdcanais.com/ufcfightpass', imageUrl: '', color: '#ef4444', initials: 'UF' },
  { id: 'caze-tv-1', name: 'Caze TV 1', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=cazetv1', imageUrl: '', color: '#8b5cf6', initials: 'CZ' },
  { id: 'caze-tv-2', name: 'Caze TV 2', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=cazetv2', imageUrl: '', color: '#8b5cf6', initials: 'CZ' },
  { id: 'caze-tv-3', name: 'Caze TV 3', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=cazetv3', imageUrl: '', color: '#8b5cf6', initials: 'CZ' },
  { id: 'dazn-1', name: 'DAZN 1', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=dazn1', imageUrl: '', color: '#3b82f6', initials: 'D1' },
  { id: 'dazn-2', name: 'DAZN 2', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=dazn2', imageUrl: '', color: '#3b82f6', initials: 'D2' },
  { id: 'dazn-3', name: 'DAZN 3', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=dazn3', imageUrl: '', color: '#3b82f6', initials: 'D3' },
  { id: 'dazn-4', name: 'DAZN 4', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=dazn4', imageUrl: '', color: '#3b82f6', initials: 'D4' },
  { id: 'ge-tv', name: 'GE TV', category: 'Esportes', url: 'https://canais.free.nf/player/getv.html', imageUrl: '', color: '#22c55e', initials: 'GE' },
  { id: 'sportynet', name: 'Sportynet', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=sportynet', imageUrl: '', color: '#ec4899', initials: 'SN' },
  { id: 'nsports', name: 'NSports', category: 'Esportes', url: 'https://ogc-nsprt-tcl-roku-syndication.otteravision.com/ogc/nsprt/nsprt_720p.m3u8', imageUrl: '', color: '#f59e0b', initials: 'NS' },
  { id: 'xsports', name: 'XSports', category: 'Esportes', url: 'https://redecanaistv.be/player3/ch.php?canal=xsports', imageUrl: '', color: '#10b981', initials: 'XS' },

  // STREAMING
  { id: 'paramount-1', name: 'Paramount Plus 1', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=paramountplus1', imageUrl: '', color: '#3b82f6', initials: 'P1' },
  { id: 'paramount-2', name: 'Paramount Plus 2', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=paramountplus2', imageUrl: '', color: '#3b82f6', initials: 'P2' },
  { id: 'paramount-3', name: 'Paramount Plus 3', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=paramountplus3', imageUrl: '', color: '#3b82f6', initials: 'P3' },
  { id: 'paramount-4', name: 'Paramount Plus 4', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=paramountplus4', imageUrl: '', color: '#3b82f6', initials: 'P4' },
  { id: 'prime-video-1', name: 'Prime Video 1', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=primevideo1', imageUrl: '', color: '#06b6d4', initials: 'PV' },
  { id: 'prime-video-2', name: 'Prime Video 2', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=primevideo2', imageUrl: '', color: '#06b6d4', initials: 'PV' },
  { id: 'prime-video-3', name: 'Prime Video 3', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=primevideo3', imageUrl: '', color: '#06b6d4', initials: 'PV' },
  { id: 'hbo-max-1', name: 'HBO Max 1', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=hbomax1', imageUrl: '', color: '#8b5cf6', initials: 'HM' },
  { id: 'hbo-max-2', name: 'HBO Max 2', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=hbomax2', imageUrl: '', color: '#8b5cf6', initials: 'HM' },
  { id: 'hbo-max-3', name: 'HBO Max 3', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=hbomax3', imageUrl: '', color: '#8b5cf6', initials: 'HM' },
  { id: 'hbo-max-4', name: 'HBO Max 4', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=hbomax4', imageUrl: '', color: '#8b5cf6', initials: 'HM' },
  { id: 'hbo-max-5', name: 'HBO Max 5', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=hbomax5', imageUrl: '', color: '#8b5cf6', initials: 'HM' },
  { id: 'hbo-max-6', name: 'HBO Max 6', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=hbomax6', imageUrl: '', color: '#8b5cf6', initials: 'HM' },
  { id: 'hbo-max-7', name: 'HBO Max 7', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=hbomax7', imageUrl: '', color: '#8b5cf6', initials: 'HM' },
  { id: 'hbo-max-8', name: 'HBO Max 8', category: 'Streaming', url: 'https://redecanaistv.be/player3/ch.php?canal=hbomax8', imageUrl: '', color: '#8b5cf6', initials: 'HM' },

  // INFANTIL
  { id: 'cartoon-network', name: 'Cartoon Network', category: 'Infantil', url: 'https://rdcanais.com/cartoonnetwork', imageUrl: '', color: '#fb7185', initials: 'CN' },
  { id: 'cartoon-network-op2', name: 'Cartoon Network OP2', category: 'Infantil', url: 'https://redecanaistv.be/player3/ch.php?canal=cartoon', imageUrl: '', color: '#fb7185', initials: 'C2' },
  { id: 'nick-online', name: 'Nick Online', category: 'Infantil', url: 'https://x1co.com.br/hls/0/stream.m3u8?cachebust=a6809f', imageUrl: '', color: '#f59e0b', initials: 'NO' },
  { id: 'box-kids-tv', name: 'Box Kids TV', category: 'Infantil', url: 'https://redecanaistv.be/player3/ch.php?canal=boxkidstv', imageUrl: '', color: '#ec4899', initials: 'BK' },
  { id: 'cartoonito', name: 'Cartoonito', category: 'Infantil', url: 'https://redecanaistv.be/player3/ch.php?canal=cartoonito', imageUrl: '', color: '#8b5cf6', initials: 'CT' },
  { id: 'gloob', name: 'Gloob', category: 'Infantil', url: 'https://redecanaistv.be/player3/ch.php?canal=gloob', imageUrl: '', color: '#10b981', initials: 'GL' },
  { id: 'gloobinho', name: 'Gloobinho', category: 'Infantil', url: 'https://redecanaistv.be/player3/ch.php?canal=gloobinho', imageUrl: '', color: '#10b981', initials: 'GH' },
  { id: 'discovery-kids', name: 'Discovery Kids', category: 'Infantil', url: 'https://redecanaistv.be/player3/ch.php?canal=discoverykids', imageUrl: '', color: '#3b82f6', initials: 'DK' },
  { id: 'tooncast', name: 'Tooncast', category: 'Infantil', url: 'https://redecanaistv.be/player3/ch.php?canal=tooncast', imageUrl: '', color: '#f43f5e', initials: 'TC' },
  { id: 'otaku-sign-tv', name: 'Otaku Sign TV', category: 'Infantil', url: 'https://stmv1.srvif.com/anime/anime/playlist.m3u8', imageUrl: '', color: '#10b981', initials: 'OS' },
  { id: 'simpsons-24h', name: 'Os Simpsons 24h', category: 'Infantil', url: 'https://w2.embedtv.live/24h_simpsons', imageUrl: '', color: '#f59e0b', initials: 'SI' },
  { id: 'retro-cartoon', name: 'Retrô Cartoon', category: 'Infantil', url: 'https://canais.free.nf/player/retro.html', imageUrl: '', color: '#fb7185', initials: 'RC' },
  { id: 'adult-swim', name: 'Adult Swim', category: 'Infantil', url: 'https://rdcanais.com/adultswim', imageUrl: '', color: '#3b82f6', initials: 'AS' },
  { id: 'loading-tv', name: 'Loading TV', category: 'Infantil', url: 'https://canais.free.nf/player/loading.html', imageUrl: '', color: '#ec4899', initials: 'LT' },
  { id: 'gospel-cartoon', name: 'Gospel Cartoon', category: 'Infantil', url: 'https://canais.free.nf/player/gospel.html', imageUrl: '', color: '#10b981', initials: 'GC' },

  // FILMES E SÉRIES
  { id: 'hbo', name: 'HBO', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=hbo', imageUrl: '', color: '#3b82f6', initials: 'H1' },
  { id: 'hbo-op2', name: 'HBO OP2', category: 'Filmes e Séries', url: 'https://rdcanais.com/hbo', imageUrl: '', color: '#3b82f6', initials: 'H2' },
  { id: 'hbo-2', name: 'HBO 2', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=hbo2', imageUrl: '', color: '#3b82f6', initials: 'H2' },
  { id: 'hbo-family', name: 'HBO Family', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=hbofamily', imageUrl: '', color: '#3b82f6', initials: 'HF' },
  { id: 'hbo-plus', name: 'HBO Plus', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=hboplus', imageUrl: '', color: '#3b82f6', initials: 'HP' },
  { id: 'hbo-xtreme', name: 'HBO Xtreme', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=hboxtreme', imageUrl: '', color: '#3b82f6', initials: 'HX' },
  { id: 'hbo-mundi', name: 'HBO Mundi', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=hbomundi', imageUrl: '', color: '#3b82f6', initials: 'HM' },
  { id: 'hbo-pop', name: 'HBO Pop', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=hbopop', imageUrl: '', color: '#3b82f6', initials: 'HP' },
  { id: 'hbo-signature', name: 'HBO Signature', category: 'Filmes e Séries', url: 'https://rdcanais.com/hbosignature', imageUrl: '', color: '#3b82f6', initials: 'HS' },
  { id: 'tnt', name: 'TNT', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=tnt', imageUrl: '', color: '#ec4899', initials: 'TN' },
  { id: 'tnt-series', name: 'TNT Series', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=tntseries', imageUrl: '', color: '#ec4899', initials: 'TS' },
  { id: 'tnt-novelas', name: 'TNT Novelas', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=tntnovelas', imageUrl: '', color: '#ec4899', initials: 'TN' },
  { id: 'telecine-action', name: 'Telecine Action', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=telecineaction', imageUrl: '', color: '#ef4444', initials: 'TA' },
  { id: 'telecine-pipoca', name: 'Telecine Pipoca', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=telecinepipoca', imageUrl: '', color: '#ef4444', initials: 'TP' },
  { id: 'telecine-premium', name: 'Telecine Premium', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=telecinepremium', imageUrl: '', color: '#ef4444', initials: 'TP' },
  { id: 'telecine-touch', name: 'Telecine Touch', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=telecinetouch', imageUrl: '', color: '#ef4444', initials: 'TT' },
  { id: 'telecine-fun', name: 'Telecine Fun', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=telecinefun', imageUrl: '', color: '#ef4444', initials: 'TF' },
  { id: 'telecine-cult', name: 'Telecine Cult', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=telecinecult', imageUrl: '', color: '#ef4444', initials: 'TC' },
  { id: 'cinemax', name: 'Cinemax', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=cinemax', imageUrl: '', color: '#f59e0b', initials: 'CX' },
  { id: 'axn', name: 'AXN', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=axn', imageUrl: '', color: '#10b981', initials: 'AX' },
  { id: 'amc', name: 'AMC', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=amc', imageUrl: '', color: '#f59e0b', initials: 'AM' },
  { id: 'amc-series', name: 'AMC Series', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=amcseries', imageUrl: '', color: '#f59e0b', initials: 'AS' },
  { id: 'space', name: 'Space', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=space', imageUrl: '', color: '#3b82f6', initials: 'SP' },
  { id: 'warner-tv', name: 'Warner TV', category: 'Filmes e Séries', url: 'https://rdcanais.com/warnertv', imageUrl: '', color: '#f59e0b', initials: 'WT' },
  { id: 'sony', name: 'Sony', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=sony', imageUrl: '', color: '#ef4444', initials: 'SO' },
  { id: 'sony-movies', name: 'Sony Movies', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=sonymovies', imageUrl: '', color: '#ef4444', initials: 'SM' },
  { id: 'studio-universal', name: 'Studio Universal', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=studiouniversal', imageUrl: '', color: '#3b82f6', initials: 'SU' },
  { id: 'universal-tv', name: 'Universal TV', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=universal', imageUrl: '', color: '#3b82f6', initials: 'UT' },
  { id: 'megapix', name: 'Megapix', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=megapix', imageUrl: '', color: '#10b981', initials: 'MP' },
  { id: 'classique-tv-faroeste', name: 'Classique TV Faroeste', category: 'Filmes e Séries', url: 'https://canais.free.nf/player/classique.html', imageUrl: '', color: '#f59e0b', initials: 'CF' },
  { id: 'tv-classicos', name: 'TV Clássicos', category: 'Filmes e Séries', url: 'https://canais.free.nf/player/classicos.html', imageUrl: '', color: '#ec4899', initials: 'TC' },
  { id: 'globoplay-novelas', name: 'Globoplay Novelas', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=globoplaynovelas', imageUrl: '', color: '#ef4444', initials: 'GN' },
  { id: 'multishow', name: 'Multishow', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=multishow', imageUrl: '', color: '#f59e0b', initials: 'MS' },
  { id: 'canal-brasil', name: 'Canal Brasil', category: 'Filmes e Séries', url: 'https://redecanaistv.be/player3/ch.php?canal=canalbrasil', imageUrl: '', color: '#3b82f6', initials: 'CB' },
  { id: 'moviesphere-brazil', name: 'Moviesphere Brazil', category: 'Filmes e Séries', url: 'https://canais.free.nf/player/movie.html', imageUrl: '', color: '#10b981', initials: 'MB' },
  { id: 'runtime-acao', name: 'Runtime Ação', category: 'Filmes e Séries', url: 'https://canais.free.nf/player/runtime.html', imageUrl: '', color: '#ef4444', initials: 'RA' },
  { id: 'sony-one-classics', name: 'Sony One Classics', category: 'Filmes e Séries', url: 'https://canais.free.nf/player/sony.html', imageUrl: '', color: '#3b82f6', initials: 'SO' },

  // RELIGIOSOS
  { id: 'tv-aparecida', name: 'TV Aparecida', category: 'Religiosos', url: 'https://rdcanais.com/aparecida', imageUrl: '', color: '#0ea5e9', initials: 'AP' },
  { id: 'rede-vida', name: 'Rede Vida', category: 'Religiosos', url: 'https://canais.free.nf/player/redevida.html', imageUrl: '', color: '#22c55e', initials: 'RV' },
  { id: 'tv-pai-eterno', name: 'TV Pai Eterno', category: 'Religiosos', url: 'https://canais.free.nf/player/pai.html', imageUrl: '', color: '#f59e0b', initials: 'PE' },
  { id: 'cancao-nova', name: 'Canção Nova', category: 'Religiosos', url: 'https://redecanaistv.be/player3/ch.php?canal=cancaonova', imageUrl: '', color: '#3b82f6', initials: 'CN' },
  { id: 'tv-evangelizar', name: 'TV Evangelizar', category: 'Religiosos', url: 'https://redecanaistv.be/player3/ch.php?canal=tvevangelizar', imageUrl: '', color: '#ec4899', initials: 'EV' },
  { id: 'rede-gospel', name: 'Rede Gospel', category: 'Religiosos', url: 'https://player.jmvstream.com/lvw/iXRdpciRZ54XpJFH6iKiWjpBjtunNc', imageUrl: '', color: '#10b981', initials: 'RG' },
  { id: 'tv-novo-tempo', name: 'TV Novo Tempo', category: 'Religiosos', url: 'https://anym3u8player.com/tv/p.php?url=https://streamtv.novotempo.com/CDN-TV-PT/smil:tvnovotempo.smil/playlist.m3u8', imageUrl: '', color: '#0ea5e9', initials: 'NT' },
  { id: 'tv-seculo-21', name: 'TV Século 21', category: 'Religiosos', url: 'https://player.jmvstream.com/lvw/214WR13Z0vaAD3Ui2l1qYFJ6Vqtpiz', imageUrl: '', color: '#f43f5e', initials: 'S2' },

  // DOCUMENTÁRIOS
  { id: 'discovery-channel', name: 'Discovery Channel', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=discovery', imageUrl: '', color: '#3b82f6', initials: 'DC' },
  { id: 'discovery-science', name: 'Discovery Science', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=discoverysience', imageUrl: '', color: '#3b82f6', initials: 'DS' },
  { id: 'discovery-turbo', name: 'Discovery Turbo', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=discoveryturbo', imageUrl: '', color: '#3b82f6', initials: 'DT' },
  { id: 'discovery-theater', name: 'Discovery Theater', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=discoverytheater', imageUrl: '', color: '#3b82f6', initials: 'DT' },
  { id: 'discovery-world', name: 'Discovery World', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=discoveryworld', imageUrl: '', color: '#3b82f6', initials: 'DW' },
  { id: 'discovery-hh', name: 'Discovery H&H', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=discoveryhomeihealth', imageUrl: '', color: '#10b981', initials: 'HH' },
  { id: 'discovery-id', name: 'Discovery ID', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=investigacaodiscovery', imageUrl: '', color: '#ef4444', initials: 'ID' },
  { id: 'history-channel', name: 'History Channel', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=history', imageUrl: '', color: '#f59e0b', initials: 'HC' },
  { id: 'history-2', name: 'History 2', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=history2', imageUrl: '', color: '#f59e0b', initials: 'H2' },
  { id: 'animal-planet', name: 'Animal Planet', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=animalplanet', imageUrl: '', color: '#22c55e', initials: 'AP' },
  { id: 'nat-geo-animals', name: 'Nat Geo Animals', category: 'Documentários', url: 'https://canais.free.nf/player/natgeo.html', imageUrl: '', color: '#f59e0b', initials: 'NG' },
  { id: 'tlc', name: 'TLC', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=tlc', imageUrl: '', color: '#ec4899', initials: 'TL' },
  { id: 'ae', name: 'A&E', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=aie', imageUrl: '', color: '#0ea5e9', initials: 'AE' },
  { id: 'gnt', name: 'GNT', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=gnt', imageUrl: '', color: '#f43f5e', initials: 'GN' },
  { id: 'usa', name: 'USA', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=usa', imageUrl: '', color: '#3b82f6', initials: 'US' },
  { id: 'lifetime', name: 'Lifetime', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=lifetime', imageUrl: '', color: '#ec4899', initials: 'LT' },
  { id: 'food-network', name: 'Food Network', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=foodnetwork', imageUrl: '', color: '#f59e0b', initials: 'FN' },
  { id: 'hgtv', name: 'HGTV', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=hgtv', imageUrl: '', color: '#22c55e', initials: 'HG' },
  { id: 'modo-viagem', name: 'Modo Viagem', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=modoviagem', imageUrl: '', color: '#3b82f6', initials: 'MV' },
  { id: 'travel-box-brazil', name: 'Travel Box Brazil', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=travelboxbrazil', imageUrl: '', color: '#0ea5e9', initials: 'TB' },
  { id: 'canal-off', name: 'Canal Off', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=off', imageUrl: '', color: '#06b6d4', initials: 'OF' },
  { id: 'curta', name: 'Curta!', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=curta', imageUrl: '', color: '#10b981', initials: 'CU' },
  { id: 'arte-1', name: 'Arte 1', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=arte1', imageUrl: '', color: '#8b5cf6', initials: 'A1' },
  { id: 'terraviva', name: 'Terraviva', category: 'Documentários', url: 'https://geo.dailymotion.com/player.html?video=x8qceqq', imageUrl: '', color: '#22c55e', initials: 'TV' },
  { id: 'bis', name: 'Bis', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=bis', imageUrl: '', color: '#3b82f6', initials: 'BI' },
  { id: 'prime-box-brazil', name: 'Prime Box Brazil', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=primeboxbrazil', imageUrl: '', color: '#0ea5e9', initials: 'PB' },
  { id: 'fish-tv', name: 'Fish TV', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=fishtv', imageUrl: '', color: '#06b6d4', initials: 'FT' },
  { id: 'canal-rural', name: 'Canal Rural', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=canalrural', imageUrl: '', color: '#f59e0b', initials: 'CR' },
  { id: 'sabor-arte', name: 'Sabor & Arte', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=saboriarte', imageUrl: '', color: '#ec4899', initials: 'SA' },
  { id: 'dog-tv', name: 'Dog TV', category: 'Documentários', url: 'https://redecanaistv.be/player3/ch.php?canal=dogtv', imageUrl: '', color: '#f59e0b', initials: 'DT' },

  // MÚSICA
  { id: 'top-tv', name: 'Top TV', category: 'Música', url: 'https://canais.free.nf/player/toptv.html', imageUrl: '', color: '#3b82f6', initials: 'TT' },
  { id: 'radio-rock', name: '89 A Rádio Rock', category: 'Música', url: 'https://geo.dailymotion.com/player/xgrus.html?video=x7wjrui', imageUrl: '', color: '#3b82f6', initials: '89' },
  { id: 'agitomax', name: 'Agitomax', category: 'Música', url: 'https://playerv.samcast.com.br/video/agitomax/6/true/false/YzNSdGRqSXVjMkZ0WTJGemRDNWpiMjB1WW5JPSta/16:9//nao/nao', imageUrl: '', color: '#f59e0b', initials: 'AM' },
  { id: 'playtv', name: 'PlayTV', category: 'Música', url: 'https://isaocorp.cloudecast.com/playtv/embed.html', imageUrl: '', color: '#8b5cf6', initials: 'PT' },
  { id: 'music-box-brazil', name: 'Music Box Brazil', category: 'Música', url: 'https://redecanaistv.be/player3/ch.php?canal=musicboxbrazil', imageUrl: '', color: '#0ea5e9', initials: 'MB' },
  { id: 'now-rock', name: 'Now Rock', category: 'Música', url: 'https://canais.free.nf/player/rock.html', imageUrl: '', color: '#3b82f6', initials: 'NR' },
  { id: 'retro-music', name: 'Retro Music', category: 'Música', url: 'https://anym3u8player.com/tv/p.php?url=https://newstream.mediawork.cz/retrotv/smil:retrotv_new.smil/playlist.m3u8', imageUrl: '', color: '#ec4899', initials: 'RM' },
  { id: 'trace-urban', name: 'Trace Urban', category: 'Música', url: 'https://anym3u8player.com/tv/p.php?url=https://amg01076-lightningintern-traceurban-xiaomi-m78n3.amagi.tv/playlist/amg01076-lightningintern-traceurban-xiaomi/playlist.m3u8', imageUrl: '', color: '#06b6d4', initials: 'TU' },
  { id: 'trace-brazuca', name: 'Trace Brazuca', category: 'Música', url: 'https://anym3u8player.com/tv/p.php?url=https://amg01131-tracetv-tracebrazuca-xiaomi-vvr19.amagi.tv/playlist/amg01131-tracetv-tracebrazuca-xiaomi/playlist.m3u8', imageUrl: '', color: '#10b981', initials: 'TB' },
  { id: 'vevo-80s', name: 'VEVO 80s', category: 'Música', url: 'https://anym3u8player.com/tv/p.php?url=https://amg00056-vevotv-vevo80saunz-samsungau-rp5e3.amagi.tv/playlist/amg00056-vevotv-vevo80saunz-samsungau/playlist.m3u8', imageUrl: '', color: '#ef4444', initials: 'V8' },
];


